application:
  env: local
  host: 0.0.0.0
  port: 9251

mysqldb:
  ip: 192.168.2.240
  port: 5306
  username: root
  password:
  database:

mongodb:
  ip: 192.168.2.240
  port: 11708
  username:
  password:
  options:
  database:

redis:
  hostname: 192.168.2.240
  port: 6379
  database: 0
  password:

oss:
  url:

apiHost:
  storeapiMicro: http://cst-micro-store.local
  groupapiMicro: http://cst-micro.local
  storeapi: http://127.0.0.1:8302
  groupapi: http://127.0.0.1:8301

intranet:
  ip: http://127.0.0.1
